# NOTE: For maximum performance, build using a nightly compiler
# If you are using rust stable, remove the "-Zshare-generics=y" below.

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

# # NOTE: you must manually install https://github.com/michaeleisel/zld on mac. you can easily do this with the "brew" package manager:
# # `brew install michaeleisel/zld/zld`
# [target.x86_64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld", "-Zshare-generics=y"]

# [target.aarch64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld", "-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
# needs nightly for -Z options
# $> rustup override set nightly-msvc

linker = "lld-link.exe"
# linker = "rust-lld.exe"

rustflags = [
  # "-Zunstable-options",
  "-Ctarget-cpu=native",
  "-Ctarget-feature=-crt-static",
  # "-Zshare-generics=y"
]

[target.x86_64-pc-windows-gnu]
# needs nightly for -Z options
# $> rustup override set nightly-msvc

linker = "lld-link.exe"
# linker = "rust-lld.exe"

rustflags = [
  # "-Zunstable-options",
  "-Ctarget-cpu=native",
  "-Ctarget-feature=-crt-static",
  # "-Zshare-generics=y"
]
